# Generated by Django 2.2.3 on 2019-08-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyServicePurchased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('per_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('unit_total', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('subsidiary_vat', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('vat_per_unit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('price_after_vat', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
