# Generated by Django 2.2.3 on 2019-08-28 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_and_service', '0003_auto_20190826_1134'),
        ('parties', '0013_auto_20190825_1143'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('unit', 'Unit'), ('kg', 'KG'), ('gm', 'Gram'), ('mg', 'Mili Gram'), ('ltr', 'Liter'), ('cm', 'Centimetre'), ('meter', 'Meter')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=50)),
                ('per_unit_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('unit_total', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('subsidiary_vat', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('vat_per_unit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('price_after_vat', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('order_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parties.Customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_and_service.Service')),
            ],
        ),
    ]
