# Generated by Django 2.2.3 on 2019-08-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='product',
            new_name='Service',
        ),
    ]
