# Generated by Django 2.2.3 on 2019-08-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190828_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='Service',
            new_name='service',
        ),
    ]
