# Generated by Django 2.2.3 on 2019-08-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20190828_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='company',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='unit_type',
        ),
    ]
