# Generated by Django 2.2.3 on 2019-09-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20190828_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='per_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
