# Generated by Django 2.2.3 on 2019-09-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_and_service', '0003_auto_20190826_1134'),
        ('parties', '0013_auto_20190825_1143'),
        ('sales', '0006_auto_20190902_0918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesInvoice',
            new_name='Sales',
        ),
    ]
