# Generated by Django 2.2.3 on 2019-09-15 10:12

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='invoice_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceNumber', to='sales.SalesInvoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
