# Generated by Django 2.2.3 on 2019-09-15 10:26

from django.db import migrations
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20190915_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), unique=True),
        ),
    ]
