# Generated by Django 2.2.3 on 2019-09-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20190915_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='invoice_number',
        ),
    ]
