# Generated by Django 2.2.3 on 2019-09-15 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_remove_salesinvoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='id',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
