# Generated by Django 2.2.3 on 2019-09-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20190915_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='invoice_number',
            new_name='invoice',
        ),
    ]
