# Generated by Django 2.2.3 on 2019-09-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20190915_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='SalesInvoice',
        ),
    ]
