# Generated by Django 2.2.3 on 2019-09-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20190915_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.SalesInvoice'),
        ),
    ]
