# Generated by Django 2.2.3 on 2019-09-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20190916_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
