# Generated by Django 2.2.3 on 2019-08-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0012_auto_20190825_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('code', models.IntegerField(unique=True)),
                ('type', models.CharField(choices=[('On Demand Service', 'On Demand Service'), ('Recurrent Service', 'Recurrent Service')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_code', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=100)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('sell_discount', models.IntegerField(blank=True, default=0, null=True)),
                ('step_size', models.IntegerField(default=1)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('purchase_discount', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_of_measurement', models.CharField(max_length=10)),
                ('vat', models.IntegerField(blank=True, default=0, null=True)),
                ('so', models.BooleanField(default=True)),
                ('po', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor', to='parties.Vendors')),
                ('service_item_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serviceitem', to='product_and_service.ServiceItem')),
            ],
        ),
    ]
