# Generated by Django 2.2.3 on 2019-08-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_and_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='type',
            field=models.CharField(choices=[('On Demand Service', 'On Demand Service'), ('Recurrent Service', 'Recurrent Service')], max_length=30),
        ),
    ]
