# Generated by Django 2.2.3 on 2019-08-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_and_service', '0002_auto_20190826_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='item_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit_of_measurement',
            field=models.CharField(choices=[('unit', 'Unit'), ('kg', 'KG'), ('gm', 'Gram'), ('mg', 'Mili Gram'), ('ltr', 'Liter'), ('cm', 'Centimetre'), ('meter', 'Meter')], max_length=10),
        ),
    ]
