# Generated by Django 2.2.3 on 2020-03-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20200317_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='data',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
