# Generated by Django 2.2.3 on 2020-03-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_auto_20200318_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='performance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
