# Generated by Django 2.2.3 on 2020-03-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_video_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='statistics',
        ),
        migrations.AddField(
            model_name='video',
            name='comment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='dislike_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='favorite_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
