# Generated by Django 2.2.3 on 2020-03-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_auto_20200318_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='performance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
