# Generated by Django 2.2.3 on 2019-07-31 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190731_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
