# Generated by Django 2.2.3 on 2019-08-21 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_banks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('sub_type', models.CharField(max_length=50)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('pin_number', models.IntegerField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(max_length=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('funded_on', models.DateField(blank=True, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=20, null=True)),
                ('vat_registration_no', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship', models.CharField(choices=[('indi', 'Idividual'), ('B2B', 'Business 2 Business'), ('B2P', 'Business 2 Person'), ('P2P', 'Person 2 Person'), ('P2B', 'Person 2 Business')], default='indi', max_length=10)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('contact_person_name', models.CharField(max_length=30)),
                ('contact_person_mobile', models.CharField(max_length=14)),
                ('contact_person_email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Banks')),
            ],
        ),
    ]
