# Generated by Django 2.2.3 on 2019-08-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_auto_20190821_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='relationship',
            field=models.CharField(choices=[('individual', 'Idividual'), ('B2B', 'Business 2 Business'), ('B2P', 'Business 2 Person'), ('P2P', 'Person 2 Person'), ('P2B', 'Person 2 Business')], default='indi', max_length=10),
        ),
    ]
