# Generated by Django 2.2.3 on 2019-08-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_banks'),
        ('parties', '0003_auto_20190821_0510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Customers',
        ),
    ]
