# Generated by Django 2.2.3 on 2019-08-21 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_auto_20190821_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='common.Banks'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='contact_person_mobile',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='relationship',
            field=models.CharField(choices=[('individual', 'Idividual'), ('B2B', 'Business 2 Business'), ('B2P', 'Business 2 Person'), ('P2P', 'Person 2 Person'), ('P2B', 'Person 2 Business')], default='B2B', max_length=10),
        ),
    ]
