# Generated by Django 2.2.3 on 2019-08-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_banks'),
        ('parties', '0005_auto_20190821_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sub_type', models.IntegerField(choices=[(1, 'Individual'), (2, 'Organization')])),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('pin_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(max_length=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('funded_on', models.DateField(blank=True, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=20, null=True)),
                ('vat_registration_no', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship', models.CharField(choices=[('individual', 'Idividual'), ('B2B', 'Business 2 Business'), ('B2P', 'Business 2 Person'), ('P2P', 'Person 2 Person'), ('P2B', 'Person 2 Business')], default='B2B', max_length=10)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_start_date', models.DateField(blank=True, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_person_mobile', models.CharField(blank=True, max_length=14, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='common.Banks')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_category', to='parties.VendorCategory')),
            ],
        ),
    ]
