# Generated by Django 2.2.3 on 2019-08-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_vendorcategory_vendors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendors',
            old_name='funded_on',
            new_name='founded_on',
        ),
    ]
