# Generated by Django 2.2.3 on 2019-08-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0007_auto_20190824_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='funded_on',
            new_name='founded_on',
        ),
        migrations.AddField(
            model_name='customers',
            name='billing_address',
            field=models.TextField(default='Dummy Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='shipping_address',
            field=models.TextField(default='Dummy Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_category', to='parties.CustomerCategory'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='sub_type',
            field=models.IntegerField(choices=[(1, 'Individual'), (2, 'Organization')]),
        ),
    ]
