# Generated by Django 2.2.3 on 2019-08-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_auto_20190824_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Banks'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Banks'),
        ),
    ]
