# Generated by Django 2.2.3 on 2019-08-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0009_auto_20190824_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='contact_person_email',
            field=models.EmailField(default='a', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='contact_person_mobile',
            field=models.CharField(default='a', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='contact_person_name',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendors',
            name='contact_person_email',
            field=models.EmailField(default='a', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendors',
            name='contact_person_mobile',
            field=models.CharField(default='a', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendors',
            name='contact_person_name',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
    ]
