# Generated by Django 2.2.3 on 2019-08-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0011_auto_20190824_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='pin_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='pin_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
