# Generated by Django 2.2.3 on 2019-08-25 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0012_auto_20190825_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='parties.VendorCategory'),
        ),
    ]
