# Generated by Django 2.2.3 on 2019-08-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imported_files')),
                ('file_type', models.CharField(choices=[('sales-order', 'Sales Order'), ('customer', 'Customer'), ('item', 'Item'), ('price_declaration', 'Price Declaration'), ('stock', 'Stock'), ('vendor', 'Vendor')], default=None, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
