# Generated by Django 2.2.3 on 2019-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190804_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file_type',
            field=models.CharField(choices=[('sales-order', 'Sales Order'), ('customer', 'Customer'), ('item', 'Item'), ('price_declaration', 'Price Declaration'), ('stock', 'Stock'), ('vendor', 'Vendor')], default=None, max_length=20),
        ),
    ]
