# Generated by Django 2.2.3 on 2019-09-14 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0005_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Company')),
            ],
            options={
                'unique_together': {('company', 'name'), ('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('reorder_level', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('unit', 'Unit'), ('kg', 'KG'), ('gm', 'Gram'), ('mg', 'Mili Gram'), ('ltr', 'Liter'), ('cm', 'Centimetre'), ('meter', 'Meter')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryType', to='inventory.InventoryType')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
    ]
